[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["KiKoS"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.3.0"
num_cpus="1.13.0"
image = "0.23.7"
clap="2.33.1"
rayon ="1.3.1"